# Generated by Django 3.2.4 on 2021-07-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'parent_post')},
        ),
    ]
