# Generated by Django 3.2.4 on 2021-06-09 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='Seller',
        ),
        migrations.AddField(
            model_name='listing',
            name='Product Description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
